#+TITLE: FinTech
#+AUTHOR: renpeng
#+OPTIONS: toc:2

** 金融行业
*** 领域模块
1. 交易订单管理
2. 渠道管理
3. 资金管理，对账，调账，清结算
4. 风控反洗钱
5. 核心账户（会计记账）

*** 核心账户服务架构解析
1. 事务管理器。提供事务api，调度子事务，保证子事务序列状态一致
2. 资源服务。即操作db的服务
2. 差错服务，在分布式事务异常时进行回滚冲正；
3. 远程日志。交易前将订单号发送到备机房锁单，交易完成后异步勾兑解锁。这么做是防止交易中主机房故障，请求发送备机房导致状态不一致。
4. 异步入账

*** 分布式事务
在条件允许的情况下，我们应该尽可能地使用单机事务，因为单机事务里，无需额外协调其他数据源，减少了网络交互时间消耗以及协调时所需的存储IO消耗，在修改等量业务数据的情况下，单机事务将会有更高的性能。
但单机数据库由于 业务逻辑解耦等因素进行了数据库垂直拆分、或者由于单机数据库性能压力等因素进行了数据库水平拆分之后，数据分布于多个数据库，这时若需要对多个数据库的数据进行协调变更，则需要引入分布式事务。


分布式实现方式有多种
1. 基于TCC（PCR）。用业务流程模拟2PC，应用广泛，开发量适中。
2. 基于消息。开发量小，业务形态简单。
3. 基于补偿。创建订单但不提交事务，等另一个请求成功再提交，失败则回滚。
4. 基于SAGA。SAGA可以看做一个异步的、利用队列实现的补偿事务。其适用于无需马上返回业务发起方最终状态的场景，例如：你的请求已提交，请稍后查询或留意通知 之类。
4. 基于2PC。db层分布式事务，如XA

**** TCC两种模式
1. 减钱一方的T阶段扣减资源，Commit阶段空提交，cancel阶段加回资源；加钱一方的T阶段空提交，Commit阶段加资源，cancel阶段空提交

2. 减钱一方的T阶段冻结部分可用余额，即减少可用余额，增加冻结金额。confirm阶段扣除冻结金额。cancel阶段扣减冻结余额，加回可用余额；加钱一方同上面一样。

***** 转账金额操作顺序
  先减后加

** 区块链2.0

数字货币的应用优势
1. 降低货币发行和流程成本
2. 提高支付清算效率
3. 提高交易的透明性和便利性
4. 减少洗钱偷税漏税的风险

数字货币的技术路线分基于账户和不基于账户两种，也可以分层共用。区块链技术是一种可选方案。

区块链技术分布式记账、不基于账户、无法被篡改，但是目前区块链占用资源过多，无论是计算资源还是存储资源

区块链
区块链是一种全新的信用系统，是一种分布式数据库系统。
trustless（无须信用）的系统，本身实现了自己的信用，这个信用是机器自己实现，使用者无法更改

智能合约
一个智能合约就是能够执行合约条款的计算机化的交易协议

*** 区块链的未来应用
区块链在信用和征信的应用
信用即资产
金融的本质，信用和风险
管理和控制风险

区块链在金融行业其他应用
共享账本（超级账本）


** 区块链系统的dact特性
D 分布式
A 自治的
C 安装合约执行
T 可追溯

工作量证明pow

** 比特币
地址

锁定脚本：放置在输出上面的花费条件。往往包含有公钥或比特币地址。
解锁脚本：“解决”或满足被锁定脚本在一个输出上设定的花费条件的脚本。它将允许输出被花费（作为下一个交易的输入）。作为每一笔比特币交易的输入，含有由用户私钥生成的签名

** 以太坊
区块链（以太坊）中的密码学
公钥和私钥之间存在数学关系，允许私钥用于在消息上生成签名，该签名可以在不公开私钥的情况下使用公钥验证。
使用ether时，当前所有者在交易中呈现他的公钥和签名。通过公钥和签名，以太坊网络中每个人都可以独立验证并接受交易的有效性，从而确认在转移ether的人确认拥有它们。

*** 钱包
关于以太坊的一个常见误解是以太坊钱包包含ether或代币。实际上，钱包只包含密钥。ether或其他代币记录在以太坊区块链中。用户通过使用钱包中的密钥签署交易来控制网络上的代币。从某种意义上说，以太坊钱包是一个 钥匙串 keychain。

1. 非确定性钱包，随机生成的秘钥
2. 确定性钱包，由种子/助记词生成
3. HD（hierarchical deterministic）钱包，树状结构的秘钥；可以创建一系列公钥而无需访问私钥。

*** 交易
交易是由外部所有帐户发起的签名消息，由以太坊网络传输，并在以太坊区块链上进行记录（挖掘）。在这个基本定义背后，有很多令人惊讶和着迷的细节。看待交易的另一种方式是，它们是唯一可触发状态更改或导致合约在EVM中执行的东西。以太坊是一个全球的单实例状态机器，交易是唯一可以让状态机“运动”，改变状态的东西。合约不会自行运行。以太坊不会在后台运行。一切都始于交易。

以太坊交易与比特币不同，比特币追踪每一笔独立的币（UTXO），以太坊跟踪账户余额

**** nonce
交易中最重要和最少被理解的字段。

以太坊区块链根据nonce值顺序处理交易。如果中间nonce值缺失，则后面的交易都需要等待此nonce的合法交易完成

并发场景下，多个nonce可能会导致问题。


*** 智能合约


*** 共识
以太坊网络中的共识是指多个节点或代理在给定的时间点就区块链状态达成一致的能力

1. 共识度量共识度量是可测量的数据，区块链网络的节点必须在该数据上达成一致，以便为每个块中包含的数据建立并保持一致。



** 逻辑时钟
Lamport Clock
逻辑时钟的概念，本质要关注的是顺序。



** 金融知识
直接融资和间接融资
间接融资：提供方通过存款或购买银行、信托、保险等有价证券，然后由这些机构以贷款、贴现方式购买资金需求方的有价证券，从而实现资金融通的过程

金融脱媒：非中介化，资金绕开商业银行直达需求方的体外循环

*** 货币
人们持有货币的动机：交易性动机、预防性动机、投机性动机

通常，一个国家的宏观经济目标包括稳定物价、充分就业、经济增长、国际收支平衡
银行业务除了存款贷款外，还包括一些中间业务，比如结算业务、租赁业务、信托业务和信用卡业务等等
商业银行管理的三原则：安全性、流动性和盈利性

*** 货币和商业银行
货币的形式：实物货币、金属货币、信用货币，和电子货币

金本位制度和布雷顿森林体系

流通中所所需要的纸币发行量=全社会商品价格总额 % 货币流通速度

居民消费价格指数CPI，固定选取不同消费品和服务，根据每种消费品和服务各自价格变动和权重，计算出一定时间内价格水平的加权平均变化程度。
衡量物价变化水平的指标还有两个：生产价格指数PPI 和 国民生产总值平减指数GDP deflaor。计算方法与CPI大致相同，只是选取的样本不同罢了

通货膨胀 -- 劫贫济富

商业银行的三性：盈利性、安全性和流动性

一级准备现金，二级准备是短期有价证券

银行的风险:
1 信用风险，即贷款无法收回；
2 市场风险，利率汇率证券及其他资产和商品架构波动带来的损失；
3 是操作风险，有不完善或有问题的内部程序、人员及系统或外部事件带来的风险。计算方法与CPI大致相同，只是选取的样本不同罢了
4 此外还有国家风险和政策风险

通货膨胀 -- 劫贫济富


** 金融相关系统
RCMP:备付金热点账户前置系统
EPCC: 延时净额结算系统
HVPS：大额实时支付系统
NUCC：非银行支付机构清算平台，即网络版银联。网联清算有限公司，NetsUnion Clearing Corpration，是经中国人民银行批准成立的非银行支付机构网络支付清算平台的运营机构。
ACS: 中央银行会计核算数据集中系统


** 会计知识
记录是会计实务中必须采用的最基本、最重要的方法
会计凭证包含两类：
1. 原始凭证。又分外部凭证和内部凭证
2. 记账凭证。又分三种：收款凭证、付款凭证和转账凭证

收款凭证：专门为直接引起收得现金或增加银行存款的各项会计事务填用的记账凭证。
付款凭证：专门为直接引起支付现金或减少银行存款的各项会计事务填用的记账凭证。
转账凭证：为一般不涉及收付现金或增减银行存款的所有其他会计事务填用的记账凭证。

复式记账
复式记账是对每项经济活动应在记账凭证上记录其应借、应贷账户和金额，这种记录在会计上称为会计记录或分录。

借在左，贷在右
收进来的存款登记在贷主账户的右方：即贷方表示债务（应付还款项）
放出去的款项登记在借主账户的左方：即借方表示债权（应收回款项）


借贷记账法
凡资产（资产运用）的增加，负债（资金来源）的减少，利益（资金来源）的减少，损失（资金运用）的增加，记入借方
凡资产（资金运用）的减少，负债（资金来源）的增加，利益（资金来源）的增加，损失（资金运用）的减少，记入贷方

** 会计2
资产类科目：反映商业银行的资产和债权
包含现金、贵金属、存放在央行的款项、短期贷款，中期贷款，长期贷款，贴现，应收利息，短期投资，固定资产，无形资产，在建工程，延递资产等
增加记借方，减少记贷方，余额反映在借方

负债类科目：反映商业银行债权人权益
包括活期存款，定期存款，联行存放款项，保证金，应付利息，长期借款，应付债券，外汇买卖等
增加记贷方，减少记借方，余额反映在贷方

所有者权益科目：商业银行投资者对银行净资产的所有权
包括实收资本，资本公积，盈余公积，利润分配等
增加记贷方，减少记借方，余额反映在贷方

损益类科目：反映商业银行在经营过程中收入、成本和费用科目
包括利息收入，手续费及佣金收入，金融企业往来收入，投资收益，利息支出，金融企业往来支出，资产损失，营业税金及附加，所得税等科目
收入类科目增加记贷方，减少记借方，期末结算转入“本年利润”的贷方；
成本和费用科目，增加记借方，减少记贷方，期末结转于“本年利润”的借方；

资产负债共同类科目：反映和核算商业银行发生的资金往来业务，适用联行往来，资金调拨，同城票据清算等业务
包括清算资金往来，辖区往来，外汇买卖，同城票据清算，资金调拨，外汇营运资金等
经过借贷方轧差后，根据差额方向归并于资产负债表内科目，参加试算平衡。性质视科目的期末余额而定。借方余额表现为资产，贷方余额表现为负债

总结
资产=负债+所有者权益
资产=负债+所有者权益+（收入-费用）。这是反应企业财务状况和经营成果动静态结合的会计公式。在利润结之后，公式归为上式
收入-费用=（未分配）利润

*** 会计科目
表内科目：用于核算银行资金的实际增减变动，并反映在资产负债表等会计报表上。
表外科目：用于核算不涉及银行资金增减变化的重要业务事项，该类科目不反映在会计报表内。但商业银行对外已承担了经济责任，也需要另外设置一些表外科目进行反映和记录
如：应收托收款项，代收托收款项，有价单证，重要空白凭证
表外科目采用单式记账，不完全用货币度量，也不要求平衡

分户账
与银行往来的客户都银行开立存款户，这些账户是明细分类账（分户账）的账户，以存款人名字为户名，同时编列一定的账户号码。
** HyperLedger超级账本
** 闪电网络
比特币的交易网络最为人诟病的一点便是交易性能：全网每秒 7 笔的交易速度，远低于传统的金融交易系统；同时，等待 6 个块的可信确认导致约 1 个小时的最终确认时间。
闪电网络的主要思路十分简单 -- 将大量交易放到比特币区块链之外进行。该设计最早是 2015 年 2 月在论文《The Bitcoin Lightning Network: Scalable Off-Chain Instant Payments》中提出
比特币的区块链机制自身提供了很好的可信保障，但是很慢；另一方面考虑，对于大量的小额交易来说，是否真实需要这么高的可信性？闪电网络通过智能合约来完善链下的交易渠道。
核心的概念主要有两个：RSMC（Recoverable Sequence Maturity Contract）和 HTLC（Hashed Timelock Contract）。前者解决了链下交易的确认问题，后者解决了支付通道的问题

*** RSMC
Recoverable Sequence Maturity Contract，中文可以翻译为“可撤销的顺序成熟度合同”。这个词很绕，其实主要原理很简单，就是类似准备金机制
先假定交易双方之间存在一个“微支付通道”（资金池）。双方都预存一部分资金到“微支付通道”里，之后每次交易，就对交易后的资金分配方案共同进行确认，同时签字作废旧的版本。当需要提现时，将最终交易结果写到区块链网络中，被最终确认。可以看到，只有在提现时候才需要通过区块链。
任何一个版本的方案都需要经过双方的签名认证才合法。任何一方在任何时候都可以提出提现，提现需要提供一个双方都签名过的资金分配方案（意味着肯定是某次交易后的结果）。在一定时间内，如果另外一方提出证明表明这个方案其实之前被作废了（非最新的交易结果），则资金罚没给质疑成功方。这就确保了没人会拿一个旧的交易结果来提现。
另外，即使双方都确认了某次提现，首先提出提现一方的资金到账时间要晚于对方，这就鼓励大家尽量都在链外完成交易

*** HTLC
微支付通道是通过 Hashed Timelock Contract 来实现的，中文意思是“哈希的带时钟的合约”。这个其实就是限时转账。理解起来其实也很简单，通过智能合约，双方约定转账方先冻结一笔钱，并提供一个哈希值，如果在一定时间内有人能提出一个字符串，使得它哈希后的值跟已知值匹配（实际上意味着转账方授权了接收方来提现），则这笔钱转给接收方。
不太恰当的例子，约定一定时间内，有人知道了某个暗语（可以生成匹配的哈希值），就可以拿到这个指定的资金。
推广一步，甲想转账给丙，丙先发给甲一个哈希值。甲可以先跟乙签订一个合同，如果你在一定时间内能告诉我一个暗语，我就给你多少钱。乙于是跑去跟丙签订一个合同，如果你告诉我那个暗语，我就给你多少钱。丙于是告诉乙暗语，拿到乙的钱，乙又从甲拿到钱。最终达到结果是甲转账给丙。这样甲和丙之间似乎构成了一条完整的虚拟的“支付通道”。
HTLC 的机制可以扩展到多个人，大家可以想象一下，想象出来了就理解了闪电网络

** 侧链技术
为方便数字资产在不同区块链间互相转移，侧链（Sidechain）技术应运而生。简单地说，侧链就像是一条条通路，将不同的区块链互相连接在一起，以实现区块链的扩展。侧链完全独立于比特币区块链，但是这两个账本之间能够“互相操作”，实现交互

*** 元素币（Elements）
** RScoin
1. 由于薄荷糖是受信任的，因此可以避免过重的共识策略，改用2PC
