#+TITLE: FinTech
#+AUTHOR: renpeng


** 区块链2.0

数字货币的应用优势
1. 降低货币发行和流程成本
2. 提高支付清算效率
3. 提高交易的透明性和便利性
4. 减少洗钱偷税漏税的风险

数字货币的技术路线分基于账户和不基于账户两种，也可以分层共用。区块链技术是一种可选方案。

区块链技术分布式记账、不基于账户、无法被篡改，但是目前区块链占用资源过多，无论是计算资源还是存储资源

区块链
区块链是一种全新的信用系统，是一种分布式数据库系统。
trustless（无须信用）的系统，本身实现了自己的信用，这个信用是机器自己实现，使用者无法更改

智能合约
一个智能合约就是能够执行合约条款的计算机化的交易协议

*** 区块链的未来应用
区块链在信用和征信的应用
信用即资产
金融的本质，信用和风险
管理和控制风险

区块链在金融行业其他应用
共享账本（超级账本）


** 区块链系统的dact特性
D 分布式
A 自治的
C 安装合约执行
T 可追溯

工作量证明pow

** 比特币
地址

锁定脚本：放置在输出上面的花费条件。往往包含有公钥或比特币地址。
解锁脚本：“解决”或满足被锁定脚本在一个输出上设定的花费条件的脚本。它将允许输出被花费（作为下一个交易的输入）。作为每一笔比特币交易的输入，含有由用户私钥生成的签名

** 以太坊
区块链（以太坊）中的密码学
公钥和私钥之间存在数学关系，允许私钥用于在消息上生成签名，该签名可以在不公开私钥的情况下使用公钥验证。
使用ether时，当前所有者在交易中呈现他的公钥和签名。通过公钥和签名，以太坊网络中每个人都可以独立验证并接受交易的有效性，从而确认在转移ether的人确认拥有它们。




** 分布式事务
TCC两种模式
1. 减钱一方的T阶段扣减资源，Commit阶段空提交，cancel阶段加回资源；加钱一方的T阶段空提交，Commit阶段加资源，cancel阶段空提交

2. 减钱一方的T阶段冻结部分可用余额，即减少可用余额，增加冻结金额。confirm阶段扣除冻结金额。cancel阶段扣减冻结余额，加回可用余额；加钱一方同上面一样。

** 逻辑时钟
Lamport Clock
逻辑时钟的概念，本质要关注的是顺序。



** 金融知识
直接融资和间接融资
间接融资：提供方通过存款或购买银行、信托、保险等有价证券，然后由这些机构以贷款、贴现方式购买资金需求方的有价证券，从而实现资金融通的过程

金融脱媒：非中介化，资金绕开商业银行直达需求方的体外循环

*** 货币
人们持有货币的动机：交易性动机、预防性动机、投机性动机

通常，一个国家的宏观经济目标包括稳定物价、充分就业、经济增长、国际收支平衡
银行业务除了存款贷款外，还包括一些中间业务，比如结算业务、租赁业务、信托业务和信用卡业务等等
商业银行管理的三原则：安全性、流动性和盈利性

*** 货币和商业银行
货币的形式：实物货币、金属货币、信用货币，和电子货币

金本位制度和布雷顿森林体系

流通中所所需要的纸币发行量=全社会商品价格总额 % 货币流通速度

居民消费价格指数CPI，固定选取不同消费品和服务，根据每种消费品和服务各自价格变动和权重，计算出一定时间内价格水平的加权平均变化程度。
衡量物价变化水平的指标还有两个：生产价格指数PPI 和 国民生产总值平减指数GDP deflaor。计算方法与CPI大致相同，只是选取的样本不同罢了

通货膨胀 -- 劫贫济富

商业银行的三性：盈利性、安全性和流动性

一级准备现金，二级准备是短期有价证券

银行的风险:
1 信用风险，即贷款无法收回；
2 市场风险，利率汇率证券及其他资产和商品架构波动带来的损失；
3 是操作风险，有不完善或有问题的内部程序、人员及系统或外部事件带来的风险。计算方法与CPI大致相同，只是选取的样本不同罢了
4 此外还有国家风险和政策风险

通货膨胀 -- 劫贫济富


** 金融相关系统
RCMP:备付金热点账户前置系统
EPCC: 延时净额结算系统
HVPS：大额实时支付系统
NUCC：非银行支付机构清算平台，即网络版银联。网联清算有限公司，NetsUnion Clearing Corpration，是经中国人民银行批准成立的非银行支付机构网络支付清算平台的运营机构。
ACS: 中央银行会计核算数据集中系统


** 会计知识
记录是会计实务中必须采用的最基本、最重要的方法
会计凭证包含两类：
1. 原始凭证。又分外部凭证和内部凭证
2. 记账凭证。又分三种：收款凭证、付款凭证和转账凭证

收款凭证：专门为直接引起收得现金或增加银行存款的各项会计事务填用的记账凭证。
付款凭证：专门为直接引起支付现金或减少银行存款的各项会计事务填用的记账凭证。
转账凭证：为一般不涉及收付现金或增减银行存款的所有其他会计事务填用的记账凭证。

复式记账
复式记账是对每项经济活动应在记账凭证上记录其应借、应贷账户和金额，这种记录在会计上称为会计记录或分录。

借在左，贷在右
收进来的存款登记在贷主账户的右方：即贷方表示债务（应付还款项）
放出去的款项登记在借主账户的左方：即借方表示债权（应收回款项）


借贷记账法
凡资产（资产运用）的增加，负债（资金来源）的减少，利益（资金来源）的减少，损失（资金运用）的增加，记入借方
凡资产（资金运用）的减少，负债（资金来源）的增加，利益（资金来源）的增加，损失（资金运用）的减少，记入贷方

** 会计2
资产类科目：反映商业银行的资产和债权
包含现金、贵金属、存放在央行的款项、短期贷款，中期贷款，长期贷款，贴现，应收利息，短期投资，固定资产，无形资产，在建工程，延递资产等
增加记借方，减少记贷方，余额反映在借方

负债类科目：反映商业银行债权人权益
包括活期存款，定期存款，联行存放款项，保证金，应付利息，长期借款，应付债券，外汇买卖等
增加记贷方，减少记借方，余额反映在贷方

所有者权益科目：商业银行投资者对银行净资产的所有权
包括实收资本，资本公积，盈余公积，利润分配等
增加记贷方，减少记借方，余额反映在贷方

损益类科目：反映商业银行在经营过程中收入、成本和费用科目
包括利息收入，手续费及佣金收入，金融企业往来收入，投资收益，利息支出，金融企业往来支出，资产损失，营业税金及附加，所得税等科目
收入类科目增加记贷方，减少记借方，期末结算转入“本年利润”的贷方；
成本和费用科目，增加记借方，减少记贷方，期末结转于“本年利润”的借方；

资产负债共同类科目：反映和核算商业银行发生的资金往来业务，适用联行往来，资金调拨，同城票据清算等业务
包括清算资金往来，辖区往来，外汇买卖，同城票据清算，资金调拨，外汇营运资金等
经过借贷方轧差后，根据差额方向归并于资产负债表内科目，参加试算平衡。性质视科目的期末余额而定。借方余额表现为资产，贷方余额表现为负债

总结
资产=负债+所有者权益
资产=负债+所有者权益+（收入-费用）。这是反应企业财务状况和经营成果动静态结合的会计公式。在利润结之后，公式归为上式
收入-费用=（未分配）利润

*** 会计科目
表内科目：用于核算银行资金的实际增减变动，并反映在资产负债表等会计报表上。
表外科目：用于核算不涉及银行资金增减变化的重要业务事项，该类科目不反映在会计报表内。但商业银行对外已承担了经济责任，也需要另外设置一些表外科目进行反映和记录
如：应收托收款项，代收托收款项，有价单证，重要空白凭证
表外科目采用单式记账，不完全用货币度量，也不要求平衡

分户账
与银行往来的客户都银行开立存款户，这些账户是明细分类账（分户账）的账户，以存款人名字为户名，同时编列一定的账户号码。
